import type { NavNode } from "./navigation.js";

export const palaceNodes: NavNode[] = [
  { id: "great_hall", name: "Great Hall", x: 15, y: 24 },
  { id: "entrance", name: "Entrance Hall", x: 15, y: 35 },
  { id: "royal_council", name: "Royal Council Chamber", x: 5, y: 17 },
  { id: "west_junction", name: "Royal Back Hall West", x: 5, y: 12 },
  { id: "north_junction", name: "Royal Back Hall", x: 15, y: 12 },
  { id: "east_junction", name: "Royal Back Hall East", x: 25, y: 12 },
  { id: "corvin", name: "Corvin's Chamber", x: 5, y: 5 },
  { id: "royal", name: "Royal Bedchamber", x: 15, y: 5 },
  { id: "garran", name: "Garran's Chamber", x: 26, y: 5 },
  { id: "guest", name: "Nobles' Parlour", x: 5, y: 25 },
  { id: "treasury", name: "Treasury", x: 26, y: 25 },
  { id: "back_hall", name: "Palace Back Hall", x: 33, y: 28 },
  { id: "ironmark_salon", name: "Ironmark Salon", x: 41, y: 11 },
  { id: "ironmark_hall", name: "Ironmark Back Hall", x: 58, y: 13 },
  { id: "mara", name: "Mara's Chamber", x: 53, y: 7 },
  { id: "hadrik", name: "Hadrik's Chamber", x: 63, y: 7 },
  { id: "tessa", name: "Tessa's Chamber", x: 73, y: 7 },
  { id: "greenweald_solar", name: "Greenweald Solar", x: 41, y: 26 },
  { id: "greenweald_hall", name: "Greenweald Back Hall", x: 58, y: 28 },
  { id: "elinor", name: "Elinor's Chamber", x: 53, y: 22 },
  { id: "oswin", name: "Oswin's Chamber", x: 63, y: 22 },
  { id: "rowan", name: "Rowan's Chamber", x: 73, y: 22 },
  { id: "saltmere_drawing_room", name: "Saltmere Drawing Room", x: 41, y: 41 },
  { id: "saltmere_hall", name: "Saltmere Back Hall", x: 58, y: 43 },
  { id: "lucan", name: "Lucan's Chamber", x: 53, y: 37 },
  { id: "sabine", name: "Sabine's Chamber", x: 63, y: 37 },
  { id: "rook", name: "Rook's Chamber", x: 73, y: 37 },
];
