import type { NavNode } from "./navigation.js";

export const palaceNodes: NavNode[] = [
  { id: "great_hall", name: "Great Hall", x: 61, y: 24 },
  { id: "entrance", name: "Entrance Hall", x: 61, y: 35 },
  { id: "royal_council", name: "Royal Council Chamber", x: 51, y: 17 },
  { id: "west_junction", name: "Royal Back Hall West", x: 51, y: 12 },
  { id: "north_junction", name: "Royal Back Hall", x: 61, y: 12 },
  { id: "east_junction", name: "Royal Back Hall East", x: 71, y: 12 },
  { id: "corvin", name: "Corvin's Chamber", x: 51, y: 5 },
  { id: "royal", name: "Royal Bedchamber", x: 61, y: 5 },
  { id: "garran", name: "Garran's Chamber", x: 72, y: 5 },
  { id: "guest", name: "Nobles' Parlour", x: 51, y: 25 },
  { id: "treasury", name: "Treasury", x: 72, y: 25 },
  { id: "back_hall", name: "East Wing", x: 79, y: 28 },
  { id: "ironmark_salon", name: "Ironmark Salon", x: 36, y: 11 },
  { id: "ironmark_hall", name: "Ironmark Back Hall", x: 19, y: 13 },
  { id: "mara", name: "Mara's Chamber", x: 24, y: 7 },
  { id: "hadrik", name: "Hadrik's Chamber", x: 14, y: 7 },
  { id: "tessa", name: "Tessa's Chamber", x: 4, y: 7 },
  { id: "greenweald_solar", name: "Greenweald Solar", x: 36, y: 26 },
  { id: "greenweald_hall", name: "Greenweald Back Hall", x: 19, y: 28 },
  { id: "elinor", name: "Elinor's Chamber", x: 24, y: 22 },
  { id: "oswin", name: "Oswin's Chamber", x: 14, y: 22 },
  { id: "rowan", name: "Rowan's Chamber", x: 4, y: 22 },
  { id: "saltmere_drawing_room", name: "Saltmere Drawing Room", x: 87, y: 11 },
  { id: "saltmere_hall", name: "Saltmere Back Hall", x: 104, y: 13 },
  { id: "lucan", name: "Lucan's Chamber", x: 99, y: 7 },
  { id: "sabine", name: "Sabine's Chamber", x: 109, y: 7 },
  { id: "rook", name: "Rook's Chamber", x: 119, y: 7 },
  { id: "west_wing", name: "West Wing", x: 44, y: 34 },
  { id: "dining_hall", name: "Long Dining Hall", x: 103, y: 26 },
];
