/** Shared meaning of NPC currentGoal and post-conversation goalUpdate. */
export const IMMEDIATE_GOAL_GUIDANCE = `# Immediate goal for the action planner
An NPC's currentGoal is the concrete task they intend to carry out next in the world. Their longer-term ambitions and motives belong in their character context and inform dialogue; do not substitute those ambitions for an immediate task.
The action planner receives this goal, observed world state and a bounded list of available actions. It chooses actions; it does not invent abilities or write a strategic plan. Express one clear, actionable intention using explicit people, places or objects and an observable completion condition. Use direct wording and only facts the character knows. Leave pathfinding, distances and the mechanics of individual steps to the engine and planner.
For example, after agreeing to meet elsewhere while still outside: "Go into the Treasury and close its door from inside." Once there with the door closed, waiting for the player to speak is idle intent, not another planner task. The authored greeting example describes background intent while idle. Being at a destination does not establish that a conversation happened or that nobody can overhear it.
A goal can require several available actions, but should not bundle unrelated errands or an entire political ambition. If a broad ambition has become relevant, choose the concrete next task justified by the conversation. Do not invent unknown locations, completed actions, agreements or abilities to make it sound executable. Preserve meaningful conditions and the character's agency: a player's request alone is not an agreement.
NPCs begin idle even when currentGoal contains the greeting example. A non-null goalUpdate explicitly assigns work and activates Jev; null leaves the NPC idle without erasing the example or last intent. After Jev terminates, review its result and actual actions, then assign another concrete task only if warranted, or return null to remain idle. A completion report alone is not evidence that physical or social effects occurred. During conversation review, goalUpdate replaces only this immediate task. Return null when the character has not adopted a new task; a conversation ending is not itself a reason to change goals. Give the new goal as intent, not as a claim of completion, and explain the decision in reason. Return goalUpdate: null when nothing needs doing now: remaining where you already are, waiting for someone to speak or leave, being available, or reacting only if a future request or condition occurs. Jev executes concrete actions; it does not monitor conversations or schedule future reactions. Record a meaningful agreement or intention in memory if needed, without creating a task to keep it alive. Do not reissue a completed task with stay, remain, wait, until, or unless wording merely to maintain the achieved state. If there is still physical work to do (such as reaching the agreed room or closing an open door), assign only that remaining work.`;

export const IMMEDIATE_GOAL_DESCRIPTION = "The NPC's next concrete task for the action planner: explicit target and observable completion or waiting condition, grounded in known facts and intentions. Assign only work that needs doing now. If the NPC is already in place and merely waiting for someone else or a future condition, return goalUpdate: null instead of a goal object. Not their long-term ambition, passive waiting, a scripted action sequence, or a claim that the task is done.";
