/** Shared meaning of NPC currentGoal and post-conversation goalUpdate. */
export const IMMEDIATE_GOAL_GUIDANCE = `# Immediate goal for the action planner
An NPC's currentGoal is the concrete task they intend to carry out next in the world. Their longer-term ambitions and motives belong in their character context and inform dialogue; do not substitute those ambitions for an immediate task.
The action planner receives this goal, observed world state and a bounded list of available actions. It chooses actions; it does not invent abilities or write a strategic plan. Express one clear, actionable intention using explicit people, places or objects and an observable completion or waiting condition. Use direct wording and only facts the character knows. Leave pathfinding, distances and the mechanics of individual steps to the engine and planner.
For example, after agreeing to meet elsewhere: "Go to the Treasury and wait there for the player to speak with me." For receiving guests: "Remain in the Great Hall and be available to greet the visiting player." Being at a destination does not establish that a conversation happened or that nobody can overhear it.
A goal can require several available actions, but should not bundle unrelated errands or an entire political ambition. If a broad ambition has become relevant, choose the concrete next task justified by the conversation. Do not invent unknown locations, completed actions, agreements or abilities to make it sound executable. Preserve meaningful conditions and the character's agency: a player's request alone is not an agreement.
During conversation review, goalUpdate replaces only this immediate task. Return null when the character has not adopted a new task; a conversation ending is not itself a reason to change goals. Give the new goal as intent, not as a claim of completion, and explain the decision in reason. Waiting is a valid continuing task; do not invent a new errand just because the character is already in the right room.`;

export const IMMEDIATE_GOAL_DESCRIPTION = "The NPC's next concrete task for the action planner: explicit target and observable completion or waiting condition, grounded in known facts and intentions. Not their long-term ambition, a scripted action sequence, or a claim that the task is done.";
